version: "3.9"
services:
  # PostgreSQL
  db:
    container_name: postgres-container
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  # Spring Boot API
  api:
    container_name: sb-container
    image: sb-image
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_ENDPOINT: ${POSTGRES_ENDPOINT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE_NAME: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  db_data: