spring:
  application:
    name:
      api-world

  datasource:
    jdbcUrl: jdbc:postgresql://${POSTGRES_ENDPOINT}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

file:
  upload-dir: /tmp/uploads

mybatis:
  mapper-locations: classpath*:com/devtkms/apiworld/dao/*.xml
