name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test with Docker Compose
        run: |
          docker-compose up -d
          docker-compose exec api ./gradlew build --no-daemon
          docker-compose exec api ./gradlew test --no-daemon

      - name: Stop Docker containers
        run: docker-compose down